version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
    - 8080:8080
    depends_on:
      - mysql_db
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: otus-net
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_user_password
      MYSQL_ROOT_PASSWORD: root_user_password