---
version: '3.8'

services:
  db:
    container_name: 'mysql'
    image: 'mysql:8.0'
    restart: always
    ports:
     - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: otuset
  
  cache:
    container_name: 'cache'
    image: 'redis:7.0'
    ports:
     - '6379:6379'
     - '8443:8443'
     - '9443:9443'
     