server:
  port: 8080
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  username: ${DATASOURCE_USERNAME}
  password: ${DATASOURCE_PASSWORD}
  url: jdbc:mysql://${DATASOURCE_HOST}:3306/otuset
logging:
  level:
    root: info