server:
  port: 8080
datasource:
  master:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: jdbc:mysql://${DATASOURCE_HOST}:3308/otuset
  slave:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: jdbc:mysql://${DATASOURCE_HOST}:3309/otuset
logging:
  level:
    root: info